/**
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {

    public static void main(String[] args) {

        long max = 4000000;
        int prev1 = 2;
        int prev2 = 1;
        long sum = 2; // prev2 is even.

        int currTerm = Integer.MIN_VALUE;

        while (currTerm <= max) {
            currTerm = prev1 + prev2;
            if (currTerm % 2 == 0) {
                sum += currTerm;
            }
            prev2 = prev1;
            prev1 = currTerm;
        }

        System.out.println(sum);
    }
}
